# Generated by Django 4.2.7 on 2025-11-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_price_per_tie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_ties',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
