# Generated by Django 4.2.7 on 2025-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_cost_price_per_tie_order_number_of_ties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business_delivery_amount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_delivery_amount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_payment_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='packaging_boxes',
        ),
        migrations.AddField(
            model_name='order',
            name='business_delivery_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_delivery_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_payment_type',
            field=models.CharField(choices=[('customer', 'Customer Paid'), ('business', 'Business Paid'), ('shared', 'Shared Payment')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='packaging_boxes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
