# Generated by Django 4.2.7 on 2025-11-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customer_business_delivery_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('advertising', 'Advertising'), ('packaging', 'Packaging'), ('airtime_data', 'Airtime & Data'), ('ties', 'Ties')], max_length=20),
        ),
    ]
